-- 001_init.sql: complete ReLab schema.
--
-- Conventions:
--   * Identifiers are UUIDs generated by the application, never sequences.
--     Runs are created on one node and referenced from others; a database
--     sequence would force a round trip before the id is usable.
--   * Enumerations are text + CHECK, not native PG enums. Adding a value to a
--     native enum cannot run inside a transaction alongside other DDL in every
--     supported version, and CHECK constraints are trivially alterable.
--   * Every timestamp is timestamptz. The application always passes UTC.

CREATE TABLE workflows (
    id              uuid        PRIMARY KEY,
    name            text        NOT NULL,
    version         integer     NOT NULL CHECK (version > 0),
    definition_yaml text        NOT NULL,
    -- sha256 of the canonical (parsed and re-marshalled) definition, so that
    -- reformatting a YAML file does not register as a new definition.
    definition_hash text        NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),

    UNIQUE (name, version)
);

CREATE TABLE runs (
    id             uuid        PRIMARY KEY,
    -- workflow_id determines (name, version); the version is deliberately NOT
    -- duplicated here. A duplicated version column can drift from the row it
    -- points at, and the join is a primary-key lookup.
    workflow_id    uuid        NOT NULL REFERENCES workflows (id) ON DELETE RESTRICT,
    status         text        NOT NULL CHECK (status IN
                       ('CREATED', 'QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED')),
    scenario_name  text,
    -- Seed for the per-run deterministic RNG that drives fault injection.
    -- Always set, so that a run without a scenario is still reproducible.
    seed           bigint      NOT NULL,
    -- Monotonic event counter. Incremented with UPDATE ... RETURNING inside the
    -- appending transaction, which takes the row lock and makes the sequence
    -- gapless: a rolled back append rolls back the counter with it.
    event_seq      bigint      NOT NULL DEFAULT 0 CHECK (event_seq >= 0),
    correlation_id text,
    failure_reason text,
    created_at     timestamptz NOT NULL DEFAULT now(),
    started_at     timestamptz,
    completed_at   timestamptz,

    CHECK (status IN ('SUCCEEDED', 'FAILED', 'CANCELLED') = (completed_at IS NOT NULL))
);

CREATE INDEX runs_status_created_idx ON runs (status, created_at DESC);
CREATE INDEX runs_workflow_idx ON runs (workflow_id, created_at DESC);

CREATE TABLE workers (
    id             uuid        PRIMARY KEY,
    hostname       text        NOT NULL,
    version        text        NOT NULL,
    status         text        NOT NULL CHECK (status IN ('HEALTHY', 'SUSPECT', 'LOST')),
    capacity       integer     NOT NULL CHECK (capacity > 0),
    active_tasks   integer     NOT NULL DEFAULT 0 CHECK (active_tasks >= 0),
    last_heartbeat timestamptz NOT NULL,
    registered_at  timestamptz NOT NULL DEFAULT now()
);

-- The reaper scans live workers by heartbeat age; lost workers are terminal and
-- never re-examined, so they are excluded from the index.
CREATE INDEX workers_liveness_idx ON workers (last_heartbeat) WHERE status <> 'LOST';

CREATE TABLE tasks (
    id               uuid        PRIMARY KEY,
    run_id           uuid        NOT NULL REFERENCES runs (id) ON DELETE CASCADE,
    task_name        text        NOT NULL,
    -- One row per workflow step, not per attempt. The attempt counter advances
    -- in place; per-attempt history lives in task_attempts and in the event log.
    attempt          integer     NOT NULL DEFAULT 0 CHECK (attempt >= 0),
    max_attempts     integer     NOT NULL CHECK (max_attempts > 0),
    status           text        NOT NULL CHECK (status IN
                        ('PENDING', 'READY', 'LEASED', 'RUNNING', 'SUCCEEDED',
                         'FAILED', 'RETRYING', 'DEAD')),
    worker_id        uuid        REFERENCES workers (id) ON DELETE SET NULL,
    lease_expires_at timestamptz,
    scheduled_at     timestamptz NOT NULL,
    started_at       timestamptz,
    completed_at     timestamptz,
    input_ref        jsonb,
    output_ref       jsonb,
    error            text,
    -- run_id:task_name:logical_op is derived at side-effect time; this column
    -- holds the task-scoped prefix so it survives worker restarts.
    idempotency_key  text        NOT NULL,
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now(),

    UNIQUE (run_id, task_name),
    -- A lease only means anything while the task is held by a worker.
    CHECK ((status IN ('LEASED', 'RUNNING')) = (lease_expires_at IS NOT NULL)),
    CHECK (status NOT IN ('LEASED', 'RUNNING') OR worker_id IS NOT NULL)
);

-- The claim query is: READY and due, ordered by scheduled_at, FOR UPDATE SKIP
-- LOCKED. A partial index keeps it proportional to the runnable set rather than
-- to the number of tasks ever created.
CREATE INDEX tasks_claimable_idx ON tasks (scheduled_at) WHERE status = 'READY';
-- The reaper scans only tasks that currently hold a lease.
CREATE INDEX tasks_lease_idx ON tasks (lease_expires_at) WHERE status IN ('LEASED', 'RUNNING');
CREATE INDEX tasks_run_idx ON tasks (run_id);

-- Append-only record of every execution start. The primary key is the
-- concurrency assertion: two workers running the same attempt of the same task
-- at the same time is a scheduler bug, and it surfaces here as a constraint
-- violation instead of as silent duplicate work. A legitimate at-least-once
-- duplicate (lease expiry while the original worker is still alive) always
-- carries a new attempt number and so does not collide.
CREATE TABLE task_attempts (
    task_id    uuid        NOT NULL REFERENCES tasks (id) ON DELETE CASCADE,
    attempt    integer     NOT NULL CHECK (attempt >= 0),
    worker_id  uuid        REFERENCES workers (id) ON DELETE SET NULL,
    started_at timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (task_id, attempt)
);

-- The event log. Source of truth for replay: no row is ever updated or deleted.
CREATE TABLE events (
    run_id      uuid        NOT NULL REFERENCES runs (id) ON DELETE CASCADE,
    seq         bigint      NOT NULL CHECK (seq > 0),
    type        text        NOT NULL,
    task_name   text,
    worker_id   uuid,
    -- Always an object, always carrying a "v" schema version. The reducer
    -- rejects a payload it cannot version rather than guessing.
    payload     jsonb       NOT NULL,
    occurred_at timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (run_id, seq),
    CHECK (jsonb_typeof(payload) = 'object')
);

-- worker_id is intentionally not a foreign key: the event log outlives the
-- worker rows it references, and a purge of dead workers must not rewrite
-- history. Same reasoning applies to task_name, which is a string in the log.

CREATE TABLE side_effects (
    idempotency_key text        PRIMARY KEY,
    run_id          uuid        NOT NULL REFERENCES runs (id) ON DELETE CASCADE,
    task_name       text        NOT NULL,
    result          jsonb       NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX side_effects_run_idx ON side_effects (run_id);

CREATE TABLE artifacts (
    id           uuid        PRIMARY KEY,
    run_id       uuid        NOT NULL REFERENCES runs (id) ON DELETE CASCADE,
    task_name    text        NOT NULL,
    name         text        NOT NULL,
    sha256       text        NOT NULL CHECK (sha256 ~ '^[0-9a-f]{64}$'),
    size         bigint      NOT NULL CHECK (size >= 0),
    content_type text        NOT NULL,
    created_at   timestamptz NOT NULL DEFAULT now(),

    -- Replay compares artifacts by (task, name); two artifacts sharing both
    -- within a run would make the comparison ambiguous.
    UNIQUE (run_id, task_name, name)
);

CREATE TABLE dead_letters (
    task_id     uuid        PRIMARY KEY REFERENCES tasks (id) ON DELETE CASCADE,
    run_id      uuid        NOT NULL REFERENCES runs (id) ON DELETE CASCADE,
    reason      text        NOT NULL,
    attempts    integer     NOT NULL CHECK (attempts > 0),
    last_worker uuid,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX dead_letters_run_idx ON dead_letters (run_id);
